# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ders_8.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 472)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 30, 431, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 481, 21))
        self.menubar.setObjectName("menubar")
        self.menuResimler = QtWidgets.QMenu(self.menubar)
        self.menuResimler.setObjectName("menuResimler")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(100, 50))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionTree = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Tree/Resimler/tree.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTree.setIcon(icon)
        self.actionTree.setObjectName("actionTree")
        self.actionGirl = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Girl/Resimler/girl.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGirl.setIcon(icon1)
        self.actionGirl.setObjectName("actionGirl")
        self.actionLion = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Lion/Resimler/lion.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLion.setIcon(icon2)
        self.actionLion.setObjectName("actionLion")
        self.menuResimler.addAction(self.actionTree)
        self.menuResimler.addAction(self.actionGirl)
        self.menuResimler.addAction(self.actionLion)
        self.menubar.addAction(self.menuResimler.menuAction())
        self.toolBar.addAction(self.actionTree)
        self.toolBar.addAction(self.actionGirl)
        self.toolBar.addAction(self.actionLion)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuResimler.setTitle(_translate("MainWindow", "Picture"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionTree.setText(_translate("MainWindow", "Tree"))
        self.actionGirl.setText(_translate("MainWindow", "Girl"))
        self.actionLion.setText(_translate("MainWindow", "Lion"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
