# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ders_6.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuAyakkab = QtWidgets.QMenu(self.menubar)
        self.menuAyakkab.setObjectName("menuAyakkab")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSpor = QtWidgets.QAction(MainWindow)
        self.actionSpor.setObjectName("actionSpor")
        self.actionC = QtWidgets.QAction(MainWindow)
        self.actionC.setObjectName("actionC")
        self.actionPython = QtWidgets.QAction(MainWindow)
        self.actionPython.setObjectName("actionPython")
        self.menuAyakkab.addAction(self.actionSpor)
        self.menuAyakkab.addAction(self.actionC)
        self.menuAyakkab.addAction(self.actionPython)
        self.menubar.addAction(self.menuAyakkab.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuAyakkab.setTitle(_translate("MainWindow", "Yazılım Dilleri"))
        self.actionSpor.setText(_translate("MainWindow", "C++"))
        self.actionSpor.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionC.setText(_translate("MainWindow", "C#"))
        self.actionC.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.actionPython.setText(_translate("MainWindow", "Python"))
        self.actionPython.setShortcut(_translate("MainWindow", "Ctrl+B"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
